### PR TITLE
[WIP] Merge facebook upstream master changes

### PR DESCRIPTION
**Pull request by Terkwood**
Hi!

I tried merging the facebook master branch changes, but I have no idea how to test them.  I had trouble getting `npm run test` working on my vagrant debian box, though I did try.  

If you can offer any tips on how to check the functionality of the creation script locally, _or_ if you want to test it out on your own box, _or_ if you want to visually inspect the changes for errors, please feel free to do so at your leisure.  

That said, I'll keep digging around and see if I can get it working locally, and just wanted to put up the PR as a WIP in the meantime.  I'm new to `create-react-app` in general and haven't gained any real depth in terms of understanding the toolset.

Cheers!

### CODE REVIEW

**Comment by Terkwood** [comment]
I made progress testing this locally (`npm run create-react-app ../foo-pkg`), but the package config doesn't seem to work.  I'll reopen another PR if I'm able to succeed.  Thanks!

**Comment by thomashorrobin** [comment]
@Terkwood I'm going to pull this branch and see if I can get it working. There's a bigger problem here though which is that I haven't been able to get good testing working on this fork.

I need to test Rust => wasm and the importing of wasm into App.js

**Comment by thomashorrobin** [comment]
Sorry for the late reply btw, I've been away 🏖

**Comment by Terkwood** [comment]
Ok, good luck! That's interesting about the testing. Proving that the wasm import works via `jest` (for instance) would definitely provide some peace of mind!

**Pull request closed without merging**
